//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GUI.QLRoCKWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QLRoCKBUSSoap", Namespace="http://tempuri.org/")]
    public partial class QLRoCKBUS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback timKiemOperationCompleted;
        
        private System.Threading.SendOrPostCallback layDSMaCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback layDSRoOperationCompleted;
        
        private System.Threading.SendOrPostCallback layTenRoOperationCompleted;
        
        private System.Threading.SendOrPostCallback KTThongTinThemRoCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemRoCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback taoMaRoOperationCompleted;
        
        private System.Threading.SendOrPostCallback suaTenRoOperationCompleted;
        
        private System.Threading.SendOrPostCallback layTTinMaCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback suaThongTinroCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback KTThongTinSuaRoCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback suaTTMaCKOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaMaCKOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QLRoCKBUS() {
            this.Url = global::GUI.Properties.Settings.Default.GUI_QLRoCKWS_QLRoCKBUS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event timKiemCompletedEventHandler timKiemCompleted;
        
        /// <remarks/>
        public event layDSMaCKCompletedEventHandler layDSMaCKCompleted;
        
        /// <remarks/>
        public event layDSRoCompletedEventHandler layDSRoCompleted;
        
        /// <remarks/>
        public event layTenRoCompletedEventHandler layTenRoCompleted;
        
        /// <remarks/>
        public event KTThongTinThemRoCKCompletedEventHandler KTThongTinThemRoCKCompleted;
        
        /// <remarks/>
        public event ThemRoCKCompletedEventHandler ThemRoCKCompleted;
        
        /// <remarks/>
        public event ThemCKCompletedEventHandler ThemCKCompleted;
        
        /// <remarks/>
        public event taoMaRoCompletedEventHandler taoMaRoCompleted;
        
        /// <remarks/>
        public event suaTenRoCompletedEventHandler suaTenRoCompleted;
        
        /// <remarks/>
        public event layTTinMaCKCompletedEventHandler layTTinMaCKCompleted;
        
        /// <remarks/>
        public event suaThongTinroCKCompletedEventHandler suaThongTinroCKCompleted;
        
        /// <remarks/>
        public event KTThongTinSuaRoCKCompletedEventHandler KTThongTinSuaRoCKCompleted;
        
        /// <remarks/>
        public event suaTTMaCKCompletedEventHandler suaTTMaCKCompleted;
        
        /// <remarks/>
        public event XoaMaCKCompletedEventHandler XoaMaCKCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/timKiem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string timKiem(string roCK) {
            object[] results = this.Invoke("timKiem", new object[] {
                        roCK});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void timKiemAsync(string roCK) {
            this.timKiemAsync(roCK, null);
        }
        
        /// <remarks/>
        public void timKiemAsync(string roCK, object userState) {
            if ((this.timKiemOperationCompleted == null)) {
                this.timKiemOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimKiemOperationCompleted);
            }
            this.InvokeAsync("timKiem", new object[] {
                        roCK}, this.timKiemOperationCompleted, userState);
        }
        
        private void OntimKiemOperationCompleted(object arg) {
            if ((this.timKiemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timKiemCompleted(this, new timKiemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/layDSMaCK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string layDSMaCK() {
            object[] results = this.Invoke("layDSMaCK", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void layDSMaCKAsync() {
            this.layDSMaCKAsync(null);
        }
        
        /// <remarks/>
        public void layDSMaCKAsync(object userState) {
            if ((this.layDSMaCKOperationCompleted == null)) {
                this.layDSMaCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlayDSMaCKOperationCompleted);
            }
            this.InvokeAsync("layDSMaCK", new object[0], this.layDSMaCKOperationCompleted, userState);
        }
        
        private void OnlayDSMaCKOperationCompleted(object arg) {
            if ((this.layDSMaCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.layDSMaCKCompleted(this, new layDSMaCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/layDSRo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string layDSRo() {
            object[] results = this.Invoke("layDSRo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void layDSRoAsync() {
            this.layDSRoAsync(null);
        }
        
        /// <remarks/>
        public void layDSRoAsync(object userState) {
            if ((this.layDSRoOperationCompleted == null)) {
                this.layDSRoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlayDSRoOperationCompleted);
            }
            this.InvokeAsync("layDSRo", new object[0], this.layDSRoOperationCompleted, userState);
        }
        
        private void OnlayDSRoOperationCompleted(object arg) {
            if ((this.layDSRoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.layDSRoCompleted(this, new layDSRoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/layTenRo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string layTenRo(string maRo) {
            object[] results = this.Invoke("layTenRo", new object[] {
                        maRo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void layTenRoAsync(string maRo) {
            this.layTenRoAsync(maRo, null);
        }
        
        /// <remarks/>
        public void layTenRoAsync(string maRo, object userState) {
            if ((this.layTenRoOperationCompleted == null)) {
                this.layTenRoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlayTenRoOperationCompleted);
            }
            this.InvokeAsync("layTenRo", new object[] {
                        maRo}, this.layTenRoOperationCompleted, userState);
        }
        
        private void OnlayTenRoOperationCompleted(object arg) {
            if ((this.layTenRoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.layTenRoCompleted(this, new layTenRoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KTThongTinThemRoCK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KTThongTinThemRoCK(string tenRo) {
            object[] results = this.Invoke("KTThongTinThemRoCK", new object[] {
                        tenRo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KTThongTinThemRoCKAsync(string tenRo) {
            this.KTThongTinThemRoCKAsync(tenRo, null);
        }
        
        /// <remarks/>
        public void KTThongTinThemRoCKAsync(string tenRo, object userState) {
            if ((this.KTThongTinThemRoCKOperationCompleted == null)) {
                this.KTThongTinThemRoCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKTThongTinThemRoCKOperationCompleted);
            }
            this.InvokeAsync("KTThongTinThemRoCK", new object[] {
                        tenRo}, this.KTThongTinThemRoCKOperationCompleted, userState);
        }
        
        private void OnKTThongTinThemRoCKOperationCompleted(object arg) {
            if ((this.KTThongTinThemRoCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KTThongTinThemRoCKCompleted(this, new KTThongTinThemRoCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemRoCK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ThemRoCK(string jsonData) {
            object[] results = this.Invoke("ThemRoCK", new object[] {
                        jsonData});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ThemRoCKAsync(string jsonData) {
            this.ThemRoCKAsync(jsonData, null);
        }
        
        /// <remarks/>
        public void ThemRoCKAsync(string jsonData, object userState) {
            if ((this.ThemRoCKOperationCompleted == null)) {
                this.ThemRoCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemRoCKOperationCompleted);
            }
            this.InvokeAsync("ThemRoCK", new object[] {
                        jsonData}, this.ThemRoCKOperationCompleted, userState);
        }
        
        private void OnThemRoCKOperationCompleted(object arg) {
            if ((this.ThemRoCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemRoCKCompleted(this, new ThemRoCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemCK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ThemCK(string jsonData) {
            object[] results = this.Invoke("ThemCK", new object[] {
                        jsonData});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ThemCKAsync(string jsonData) {
            this.ThemCKAsync(jsonData, null);
        }
        
        /// <remarks/>
        public void ThemCKAsync(string jsonData, object userState) {
            if ((this.ThemCKOperationCompleted == null)) {
                this.ThemCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemCKOperationCompleted);
            }
            this.InvokeAsync("ThemCK", new object[] {
                        jsonData}, this.ThemCKOperationCompleted, userState);
        }
        
        private void OnThemCKOperationCompleted(object arg) {
            if ((this.ThemCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemCKCompleted(this, new ThemCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/taoMaRo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string taoMaRo() {
            object[] results = this.Invoke("taoMaRo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void taoMaRoAsync() {
            this.taoMaRoAsync(null);
        }
        
        /// <remarks/>
        public void taoMaRoAsync(object userState) {
            if ((this.taoMaRoOperationCompleted == null)) {
                this.taoMaRoOperationCompleted = new System.Threading.SendOrPostCallback(this.OntaoMaRoOperationCompleted);
            }
            this.InvokeAsync("taoMaRo", new object[0], this.taoMaRoOperationCompleted, userState);
        }
        
        private void OntaoMaRoOperationCompleted(object arg) {
            if ((this.taoMaRoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.taoMaRoCompleted(this, new taoMaRoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/suaTenRo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool suaTenRo(string maRo, string tenRo) {
            object[] results = this.Invoke("suaTenRo", new object[] {
                        maRo,
                        tenRo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void suaTenRoAsync(string maRo, string tenRo) {
            this.suaTenRoAsync(maRo, tenRo, null);
        }
        
        /// <remarks/>
        public void suaTenRoAsync(string maRo, string tenRo, object userState) {
            if ((this.suaTenRoOperationCompleted == null)) {
                this.suaTenRoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsuaTenRoOperationCompleted);
            }
            this.InvokeAsync("suaTenRo", new object[] {
                        maRo,
                        tenRo}, this.suaTenRoOperationCompleted, userState);
        }
        
        private void OnsuaTenRoOperationCompleted(object arg) {
            if ((this.suaTenRoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.suaTenRoCompleted(this, new suaTenRoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/layTTinMaCK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string layTTinMaCK(string maRo) {
            object[] results = this.Invoke("layTTinMaCK", new object[] {
                        maRo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void layTTinMaCKAsync(string maRo) {
            this.layTTinMaCKAsync(maRo, null);
        }
        
        /// <remarks/>
        public void layTTinMaCKAsync(string maRo, object userState) {
            if ((this.layTTinMaCKOperationCompleted == null)) {
                this.layTTinMaCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlayTTinMaCKOperationCompleted);
            }
            this.InvokeAsync("layTTinMaCK", new object[] {
                        maRo}, this.layTTinMaCKOperationCompleted, userState);
        }
        
        private void OnlayTTinMaCKOperationCompleted(object arg) {
            if ((this.layTTinMaCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.layTTinMaCKCompleted(this, new layTTinMaCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/suaThongTinroCK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool suaThongTinroCK(string tenRo, string maRo) {
            object[] results = this.Invoke("suaThongTinroCK", new object[] {
                        tenRo,
                        maRo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void suaThongTinroCKAsync(string tenRo, string maRo) {
            this.suaThongTinroCKAsync(tenRo, maRo, null);
        }
        
        /// <remarks/>
        public void suaThongTinroCKAsync(string tenRo, string maRo, object userState) {
            if ((this.suaThongTinroCKOperationCompleted == null)) {
                this.suaThongTinroCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsuaThongTinroCKOperationCompleted);
            }
            this.InvokeAsync("suaThongTinroCK", new object[] {
                        tenRo,
                        maRo}, this.suaThongTinroCKOperationCompleted, userState);
        }
        
        private void OnsuaThongTinroCKOperationCompleted(object arg) {
            if ((this.suaThongTinroCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.suaThongTinroCKCompleted(this, new suaThongTinroCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KTThongTinSuaRoCK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KTThongTinSuaRoCK(string giaVay, string tiLeVay) {
            object[] results = this.Invoke("KTThongTinSuaRoCK", new object[] {
                        giaVay,
                        tiLeVay});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KTThongTinSuaRoCKAsync(string giaVay, string tiLeVay) {
            this.KTThongTinSuaRoCKAsync(giaVay, tiLeVay, null);
        }
        
        /// <remarks/>
        public void KTThongTinSuaRoCKAsync(string giaVay, string tiLeVay, object userState) {
            if ((this.KTThongTinSuaRoCKOperationCompleted == null)) {
                this.KTThongTinSuaRoCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKTThongTinSuaRoCKOperationCompleted);
            }
            this.InvokeAsync("KTThongTinSuaRoCK", new object[] {
                        giaVay,
                        tiLeVay}, this.KTThongTinSuaRoCKOperationCompleted, userState);
        }
        
        private void OnKTThongTinSuaRoCKOperationCompleted(object arg) {
            if ((this.KTThongTinSuaRoCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KTThongTinSuaRoCKCompleted(this, new KTThongTinSuaRoCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/suaTTMaCK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool suaTTMaCK(string maRo, string maCK, string giaVay, string tiLeVay) {
            object[] results = this.Invoke("suaTTMaCK", new object[] {
                        maRo,
                        maCK,
                        giaVay,
                        tiLeVay});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void suaTTMaCKAsync(string maRo, string maCK, string giaVay, string tiLeVay) {
            this.suaTTMaCKAsync(maRo, maCK, giaVay, tiLeVay, null);
        }
        
        /// <remarks/>
        public void suaTTMaCKAsync(string maRo, string maCK, string giaVay, string tiLeVay, object userState) {
            if ((this.suaTTMaCKOperationCompleted == null)) {
                this.suaTTMaCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsuaTTMaCKOperationCompleted);
            }
            this.InvokeAsync("suaTTMaCK", new object[] {
                        maRo,
                        maCK,
                        giaVay,
                        tiLeVay}, this.suaTTMaCKOperationCompleted, userState);
        }
        
        private void OnsuaTTMaCKOperationCompleted(object arg) {
            if ((this.suaTTMaCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.suaTTMaCKCompleted(this, new suaTTMaCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaMaCK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool XoaMaCK(string maRo, string maCK) {
            object[] results = this.Invoke("XoaMaCK", new object[] {
                        maRo,
                        maCK});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void XoaMaCKAsync(string maRo, string maCK) {
            this.XoaMaCKAsync(maRo, maCK, null);
        }
        
        /// <remarks/>
        public void XoaMaCKAsync(string maRo, string maCK, object userState) {
            if ((this.XoaMaCKOperationCompleted == null)) {
                this.XoaMaCKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaMaCKOperationCompleted);
            }
            this.InvokeAsync("XoaMaCK", new object[] {
                        maRo,
                        maCK}, this.XoaMaCKOperationCompleted, userState);
        }
        
        private void OnXoaMaCKOperationCompleted(object arg) {
            if ((this.XoaMaCKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaMaCKCompleted(this, new XoaMaCKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void timKiemCompletedEventHandler(object sender, timKiemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timKiemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timKiemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void layDSMaCKCompletedEventHandler(object sender, layDSMaCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class layDSMaCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal layDSMaCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void layDSRoCompletedEventHandler(object sender, layDSRoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class layDSRoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal layDSRoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void layTenRoCompletedEventHandler(object sender, layTenRoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class layTenRoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal layTenRoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KTThongTinThemRoCKCompletedEventHandler(object sender, KTThongTinThemRoCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KTThongTinThemRoCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KTThongTinThemRoCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ThemRoCKCompletedEventHandler(object sender, ThemRoCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemRoCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemRoCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ThemCKCompletedEventHandler(object sender, ThemCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void taoMaRoCompletedEventHandler(object sender, taoMaRoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class taoMaRoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal taoMaRoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void suaTenRoCompletedEventHandler(object sender, suaTenRoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class suaTenRoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal suaTenRoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void layTTinMaCKCompletedEventHandler(object sender, layTTinMaCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class layTTinMaCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal layTTinMaCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void suaThongTinroCKCompletedEventHandler(object sender, suaThongTinroCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class suaThongTinroCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal suaThongTinroCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KTThongTinSuaRoCKCompletedEventHandler(object sender, KTThongTinSuaRoCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KTThongTinSuaRoCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KTThongTinSuaRoCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void suaTTMaCKCompletedEventHandler(object sender, suaTTMaCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class suaTTMaCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal suaTTMaCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void XoaMaCKCompletedEventHandler(object sender, XoaMaCKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaMaCKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaMaCKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591