//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GUI.QLLuuKiWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QLLuukiBUSSoap", Namespace="http://tempuri.org/")]
    public partial class QLLuukiBUS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback timKiemOperationCompleted;
        
        private System.Threading.SendOrPostCallback KtraNopLuuKiOperationCompleted;
        
        private System.Threading.SendOrPostCallback KtraRutLuuKiOperationCompleted;
        
        private System.Threading.SendOrPostCallback nopLuuKiOperationCompleted;
        
        private System.Threading.SendOrPostCallback rutLuuKiOperationCompleted;
        
        private System.Threading.SendOrPostCallback KtraNhapSoTKLKOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QLLuukiBUS() {
            this.Url = global::GUI.Properties.Settings.Default.GUI_QLLuuKiWS_QLLuukiBUS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event timKiemCompletedEventHandler timKiemCompleted;
        
        /// <remarks/>
        public event KtraNopLuuKiCompletedEventHandler KtraNopLuuKiCompleted;
        
        /// <remarks/>
        public event KtraRutLuuKiCompletedEventHandler KtraRutLuuKiCompleted;
        
        /// <remarks/>
        public event nopLuuKiCompletedEventHandler nopLuuKiCompleted;
        
        /// <remarks/>
        public event rutLuuKiCompletedEventHandler rutLuuKiCompleted;
        
        /// <remarks/>
        public event KtraNhapSoTKLKCompletedEventHandler KtraNhapSoTKLKCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/timKiem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string timKiem(string soTKLK) {
            object[] results = this.Invoke("timKiem", new object[] {
                        soTKLK});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void timKiemAsync(string soTKLK) {
            this.timKiemAsync(soTKLK, null);
        }
        
        /// <remarks/>
        public void timKiemAsync(string soTKLK, object userState) {
            if ((this.timKiemOperationCompleted == null)) {
                this.timKiemOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimKiemOperationCompleted);
            }
            this.InvokeAsync("timKiem", new object[] {
                        soTKLK}, this.timKiemOperationCompleted, userState);
        }
        
        private void OntimKiemOperationCompleted(object arg) {
            if ((this.timKiemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timKiemCompleted(this, new timKiemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KtraNopLuuKi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KtraNopLuuKi(string soLuuKi) {
            object[] results = this.Invoke("KtraNopLuuKi", new object[] {
                        soLuuKi});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KtraNopLuuKiAsync(string soLuuKi) {
            this.KtraNopLuuKiAsync(soLuuKi, null);
        }
        
        /// <remarks/>
        public void KtraNopLuuKiAsync(string soLuuKi, object userState) {
            if ((this.KtraNopLuuKiOperationCompleted == null)) {
                this.KtraNopLuuKiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKtraNopLuuKiOperationCompleted);
            }
            this.InvokeAsync("KtraNopLuuKi", new object[] {
                        soLuuKi}, this.KtraNopLuuKiOperationCompleted, userState);
        }
        
        private void OnKtraNopLuuKiOperationCompleted(object arg) {
            if ((this.KtraNopLuuKiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KtraNopLuuKiCompleted(this, new KtraNopLuuKiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KtraRutLuuKi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KtraRutLuuKi(string soLuuKi, string soLuongToiDa) {
            object[] results = this.Invoke("KtraRutLuuKi", new object[] {
                        soLuuKi,
                        soLuongToiDa});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KtraRutLuuKiAsync(string soLuuKi, string soLuongToiDa) {
            this.KtraRutLuuKiAsync(soLuuKi, soLuongToiDa, null);
        }
        
        /// <remarks/>
        public void KtraRutLuuKiAsync(string soLuuKi, string soLuongToiDa, object userState) {
            if ((this.KtraRutLuuKiOperationCompleted == null)) {
                this.KtraRutLuuKiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKtraRutLuuKiOperationCompleted);
            }
            this.InvokeAsync("KtraRutLuuKi", new object[] {
                        soLuuKi,
                        soLuongToiDa}, this.KtraRutLuuKiOperationCompleted, userState);
        }
        
        private void OnKtraRutLuuKiOperationCompleted(object arg) {
            if ((this.KtraRutLuuKiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KtraRutLuuKiCompleted(this, new KtraRutLuuKiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/nopLuuKi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool nopLuuKi(string soTKLK, string maCK, long soLuong, long soLuongNop) {
            object[] results = this.Invoke("nopLuuKi", new object[] {
                        soTKLK,
                        maCK,
                        soLuong,
                        soLuongNop});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void nopLuuKiAsync(string soTKLK, string maCK, long soLuong, long soLuongNop) {
            this.nopLuuKiAsync(soTKLK, maCK, soLuong, soLuongNop, null);
        }
        
        /// <remarks/>
        public void nopLuuKiAsync(string soTKLK, string maCK, long soLuong, long soLuongNop, object userState) {
            if ((this.nopLuuKiOperationCompleted == null)) {
                this.nopLuuKiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnopLuuKiOperationCompleted);
            }
            this.InvokeAsync("nopLuuKi", new object[] {
                        soTKLK,
                        maCK,
                        soLuong,
                        soLuongNop}, this.nopLuuKiOperationCompleted, userState);
        }
        
        private void OnnopLuuKiOperationCompleted(object arg) {
            if ((this.nopLuuKiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nopLuuKiCompleted(this, new nopLuuKiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/rutLuuKi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool rutLuuKi(string soTKLK, string maCK, long soLuong, long soLuongRut) {
            object[] results = this.Invoke("rutLuuKi", new object[] {
                        soTKLK,
                        maCK,
                        soLuong,
                        soLuongRut});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void rutLuuKiAsync(string soTKLK, string maCK, long soLuong, long soLuongRut) {
            this.rutLuuKiAsync(soTKLK, maCK, soLuong, soLuongRut, null);
        }
        
        /// <remarks/>
        public void rutLuuKiAsync(string soTKLK, string maCK, long soLuong, long soLuongRut, object userState) {
            if ((this.rutLuuKiOperationCompleted == null)) {
                this.rutLuuKiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrutLuuKiOperationCompleted);
            }
            this.InvokeAsync("rutLuuKi", new object[] {
                        soTKLK,
                        maCK,
                        soLuong,
                        soLuongRut}, this.rutLuuKiOperationCompleted, userState);
        }
        
        private void OnrutLuuKiOperationCompleted(object arg) {
            if ((this.rutLuuKiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rutLuuKiCompleted(this, new rutLuuKiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KtraNhapSoTKLK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KtraNhapSoTKLK(string soTKLK) {
            object[] results = this.Invoke("KtraNhapSoTKLK", new object[] {
                        soTKLK});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KtraNhapSoTKLKAsync(string soTKLK) {
            this.KtraNhapSoTKLKAsync(soTKLK, null);
        }
        
        /// <remarks/>
        public void KtraNhapSoTKLKAsync(string soTKLK, object userState) {
            if ((this.KtraNhapSoTKLKOperationCompleted == null)) {
                this.KtraNhapSoTKLKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKtraNhapSoTKLKOperationCompleted);
            }
            this.InvokeAsync("KtraNhapSoTKLK", new object[] {
                        soTKLK}, this.KtraNhapSoTKLKOperationCompleted, userState);
        }
        
        private void OnKtraNhapSoTKLKOperationCompleted(object arg) {
            if ((this.KtraNhapSoTKLKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KtraNhapSoTKLKCompleted(this, new KtraNhapSoTKLKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void timKiemCompletedEventHandler(object sender, timKiemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timKiemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timKiemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KtraNopLuuKiCompletedEventHandler(object sender, KtraNopLuuKiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KtraNopLuuKiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KtraNopLuuKiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KtraRutLuuKiCompletedEventHandler(object sender, KtraRutLuuKiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KtraRutLuuKiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KtraRutLuuKiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void nopLuuKiCompletedEventHandler(object sender, nopLuuKiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nopLuuKiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nopLuuKiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void rutLuuKiCompletedEventHandler(object sender, rutLuuKiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rutLuuKiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rutLuuKiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KtraNhapSoTKLKCompletedEventHandler(object sender, KtraNhapSoTKLKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KtraNhapSoTKLKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KtraNhapSoTKLKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591