//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GUI.QLTienMatWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QLTienMatBUSSoap", Namespace="http://tempuri.org/")]
    public partial class QLTienMatBUS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback timKiemOperationCompleted;
        
        private System.Threading.SendOrPostCallback KtraNopTienOperationCompleted;
        
        private System.Threading.SendOrPostCallback KtraRutTienOperationCompleted;
        
        private System.Threading.SendOrPostCallback nopTienOperationCompleted;
        
        private System.Threading.SendOrPostCallback rutTienOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QLTienMatBUS() {
            this.Url = global::GUI.Properties.Settings.Default.GUI_QLTienMatWS_QLTienMatBUS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event timKiemCompletedEventHandler timKiemCompleted;
        
        /// <remarks/>
        public event KtraNopTienCompletedEventHandler KtraNopTienCompleted;
        
        /// <remarks/>
        public event KtraRutTienCompletedEventHandler KtraRutTienCompleted;
        
        /// <remarks/>
        public event nopTienCompletedEventHandler nopTienCompleted;
        
        /// <remarks/>
        public event rutTienCompletedEventHandler rutTienCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/timKiem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string timKiem(string soTKLK) {
            object[] results = this.Invoke("timKiem", new object[] {
                        soTKLK});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void timKiemAsync(string soTKLK) {
            this.timKiemAsync(soTKLK, null);
        }
        
        /// <remarks/>
        public void timKiemAsync(string soTKLK, object userState) {
            if ((this.timKiemOperationCompleted == null)) {
                this.timKiemOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimKiemOperationCompleted);
            }
            this.InvokeAsync("timKiem", new object[] {
                        soTKLK}, this.timKiemOperationCompleted, userState);
        }
        
        private void OntimKiemOperationCompleted(object arg) {
            if ((this.timKiemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timKiemCompleted(this, new timKiemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KtraNopTien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KtraNopTien(string soTien) {
            object[] results = this.Invoke("KtraNopTien", new object[] {
                        soTien});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KtraNopTienAsync(string soTien) {
            this.KtraNopTienAsync(soTien, null);
        }
        
        /// <remarks/>
        public void KtraNopTienAsync(string soTien, object userState) {
            if ((this.KtraNopTienOperationCompleted == null)) {
                this.KtraNopTienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKtraNopTienOperationCompleted);
            }
            this.InvokeAsync("KtraNopTien", new object[] {
                        soTien}, this.KtraNopTienOperationCompleted, userState);
        }
        
        private void OnKtraNopTienOperationCompleted(object arg) {
            if ((this.KtraNopTienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KtraNopTienCompleted(this, new KtraNopTienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KtraRutTien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KtraRutTien(string soTien, string soTienToiDa) {
            object[] results = this.Invoke("KtraRutTien", new object[] {
                        soTien,
                        soTienToiDa});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KtraRutTienAsync(string soTien, string soTienToiDa) {
            this.KtraRutTienAsync(soTien, soTienToiDa, null);
        }
        
        /// <remarks/>
        public void KtraRutTienAsync(string soTien, string soTienToiDa, object userState) {
            if ((this.KtraRutTienOperationCompleted == null)) {
                this.KtraRutTienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKtraRutTienOperationCompleted);
            }
            this.InvokeAsync("KtraRutTien", new object[] {
                        soTien,
                        soTienToiDa}, this.KtraRutTienOperationCompleted, userState);
        }
        
        private void OnKtraRutTienOperationCompleted(object arg) {
            if ((this.KtraRutTienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KtraRutTienCompleted(this, new KtraRutTienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/nopTien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool nopTien(string soTKLK, long soTienMat, long soTienNop) {
            object[] results = this.Invoke("nopTien", new object[] {
                        soTKLK,
                        soTienMat,
                        soTienNop});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void nopTienAsync(string soTKLK, long soTienMat, long soTienNop) {
            this.nopTienAsync(soTKLK, soTienMat, soTienNop, null);
        }
        
        /// <remarks/>
        public void nopTienAsync(string soTKLK, long soTienMat, long soTienNop, object userState) {
            if ((this.nopTienOperationCompleted == null)) {
                this.nopTienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnopTienOperationCompleted);
            }
            this.InvokeAsync("nopTien", new object[] {
                        soTKLK,
                        soTienMat,
                        soTienNop}, this.nopTienOperationCompleted, userState);
        }
        
        private void OnnopTienOperationCompleted(object arg) {
            if ((this.nopTienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nopTienCompleted(this, new nopTienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/rutTien", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool rutTien(string soTKLK, long soTienMat, long soTienNop) {
            object[] results = this.Invoke("rutTien", new object[] {
                        soTKLK,
                        soTienMat,
                        soTienNop});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void rutTienAsync(string soTKLK, long soTienMat, long soTienNop) {
            this.rutTienAsync(soTKLK, soTienMat, soTienNop, null);
        }
        
        /// <remarks/>
        public void rutTienAsync(string soTKLK, long soTienMat, long soTienNop, object userState) {
            if ((this.rutTienOperationCompleted == null)) {
                this.rutTienOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrutTienOperationCompleted);
            }
            this.InvokeAsync("rutTien", new object[] {
                        soTKLK,
                        soTienMat,
                        soTienNop}, this.rutTienOperationCompleted, userState);
        }
        
        private void OnrutTienOperationCompleted(object arg) {
            if ((this.rutTienCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rutTienCompleted(this, new rutTienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void timKiemCompletedEventHandler(object sender, timKiemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timKiemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timKiemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void KtraNopTienCompletedEventHandler(object sender, KtraNopTienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KtraNopTienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KtraNopTienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void KtraRutTienCompletedEventHandler(object sender, KtraRutTienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KtraRutTienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KtraRutTienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void nopTienCompletedEventHandler(object sender, nopTienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nopTienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nopTienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void rutTienCompletedEventHandler(object sender, rutTienCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rutTienCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rutTienCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591