//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GUI.QLyKHWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QLyKHBUSSoap", Namespace="http://tempuri.org/")]
    public partial class QLyKHBUS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback layDSKhachHangOperationCompleted;
        
        private System.Threading.SendOrPostCallback layMotKhachHangOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKHOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKHSDTOperationCompleted;
        
        private System.Threading.SendOrPostCallback KTThongTinThemKHOperationCompleted;
        
        private System.Threading.SendOrPostCallback KTThongTinSuaKHOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemKHOperationCompleted;
        
        private System.Threading.SendOrPostCallback layDSRoOperationCompleted;
        
        private System.Threading.SendOrPostCallback suaThongTinKHOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QLyKHBUS() {
            this.Url = global::GUI.Properties.Settings.Default.GUI_QLyKHWS_QLyKHBUS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event layDSKhachHangCompletedEventHandler layDSKhachHangCompleted;
        
        /// <remarks/>
        public event layMotKhachHangCompletedEventHandler layMotKhachHangCompleted;
        
        /// <remarks/>
        public event GetKHCompletedEventHandler GetKHCompleted;
        
        /// <remarks/>
        public event GetKHSDTCompletedEventHandler GetKHSDTCompleted;
        
        /// <remarks/>
        public event KTThongTinThemKHCompletedEventHandler KTThongTinThemKHCompleted;
        
        /// <remarks/>
        public event KTThongTinSuaKHCompletedEventHandler KTThongTinSuaKHCompleted;
        
        /// <remarks/>
        public event ThemKHCompletedEventHandler ThemKHCompleted;
        
        /// <remarks/>
        public event layDSRoCompletedEventHandler layDSRoCompleted;
        
        /// <remarks/>
        public event suaThongTinKHCompletedEventHandler suaThongTinKHCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/layDSKhachHang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string layDSKhachHang() {
            object[] results = this.Invoke("layDSKhachHang", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void layDSKhachHangAsync() {
            this.layDSKhachHangAsync(null);
        }
        
        /// <remarks/>
        public void layDSKhachHangAsync(object userState) {
            if ((this.layDSKhachHangOperationCompleted == null)) {
                this.layDSKhachHangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlayDSKhachHangOperationCompleted);
            }
            this.InvokeAsync("layDSKhachHang", new object[0], this.layDSKhachHangOperationCompleted, userState);
        }
        
        private void OnlayDSKhachHangOperationCompleted(object arg) {
            if ((this.layDSKhachHangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.layDSKhachHangCompleted(this, new layDSKhachHangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/layMotKhachHang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string layMotKhachHang(string soTKLK) {
            object[] results = this.Invoke("layMotKhachHang", new object[] {
                        soTKLK});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void layMotKhachHangAsync(string soTKLK) {
            this.layMotKhachHangAsync(soTKLK, null);
        }
        
        /// <remarks/>
        public void layMotKhachHangAsync(string soTKLK, object userState) {
            if ((this.layMotKhachHangOperationCompleted == null)) {
                this.layMotKhachHangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlayMotKhachHangOperationCompleted);
            }
            this.InvokeAsync("layMotKhachHang", new object[] {
                        soTKLK}, this.layMotKhachHangOperationCompleted, userState);
        }
        
        private void OnlayMotKhachHangOperationCompleted(object arg) {
            if ((this.layMotKhachHangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.layMotKhachHangCompleted(this, new layMotKhachHangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetKH(string soCMND) {
            object[] results = this.Invoke("GetKH", new object[] {
                        soCMND});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetKHAsync(string soCMND) {
            this.GetKHAsync(soCMND, null);
        }
        
        /// <remarks/>
        public void GetKHAsync(string soCMND, object userState) {
            if ((this.GetKHOperationCompleted == null)) {
                this.GetKHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKHOperationCompleted);
            }
            this.InvokeAsync("GetKH", new object[] {
                        soCMND}, this.GetKHOperationCompleted, userState);
        }
        
        private void OnGetKHOperationCompleted(object arg) {
            if ((this.GetKHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKHCompleted(this, new GetKHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKHSDT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetKHSDT(string SDT) {
            object[] results = this.Invoke("GetKHSDT", new object[] {
                        SDT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetKHSDTAsync(string SDT) {
            this.GetKHSDTAsync(SDT, null);
        }
        
        /// <remarks/>
        public void GetKHSDTAsync(string SDT, object userState) {
            if ((this.GetKHSDTOperationCompleted == null)) {
                this.GetKHSDTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKHSDTOperationCompleted);
            }
            this.InvokeAsync("GetKHSDT", new object[] {
                        SDT}, this.GetKHSDTOperationCompleted, userState);
        }
        
        private void OnGetKHSDTOperationCompleted(object arg) {
            if ((this.GetKHSDTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKHSDTCompleted(this, new GetKHSDTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KTThongTinThemKH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KTThongTinThemKH(string soTKLK, System.DateTime ngayMoTK, string hoTen, string email, System.DateTime ngaySinh, string noiCap, string soCMND, string diaChi, string hanMucVay, string SDT) {
            object[] results = this.Invoke("KTThongTinThemKH", new object[] {
                        soTKLK,
                        ngayMoTK,
                        hoTen,
                        email,
                        ngaySinh,
                        noiCap,
                        soCMND,
                        diaChi,
                        hanMucVay,
                        SDT});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KTThongTinThemKHAsync(string soTKLK, System.DateTime ngayMoTK, string hoTen, string email, System.DateTime ngaySinh, string noiCap, string soCMND, string diaChi, string hanMucVay, string SDT) {
            this.KTThongTinThemKHAsync(soTKLK, ngayMoTK, hoTen, email, ngaySinh, noiCap, soCMND, diaChi, hanMucVay, SDT, null);
        }
        
        /// <remarks/>
        public void KTThongTinThemKHAsync(string soTKLK, System.DateTime ngayMoTK, string hoTen, string email, System.DateTime ngaySinh, string noiCap, string soCMND, string diaChi, string hanMucVay, string SDT, object userState) {
            if ((this.KTThongTinThemKHOperationCompleted == null)) {
                this.KTThongTinThemKHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKTThongTinThemKHOperationCompleted);
            }
            this.InvokeAsync("KTThongTinThemKH", new object[] {
                        soTKLK,
                        ngayMoTK,
                        hoTen,
                        email,
                        ngaySinh,
                        noiCap,
                        soCMND,
                        diaChi,
                        hanMucVay,
                        SDT}, this.KTThongTinThemKHOperationCompleted, userState);
        }
        
        private void OnKTThongTinThemKHOperationCompleted(object arg) {
            if ((this.KTThongTinThemKHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KTThongTinThemKHCompleted(this, new KTThongTinThemKHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KTThongTinSuaKH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KTThongTinSuaKH(string soTKLK, System.DateTime ngayMoTK, string email, string hoTen, System.DateTime ngaySinh, string noiCap, string soCMND, string diaChi, string hanMucVay, string SDT) {
            object[] results = this.Invoke("KTThongTinSuaKH", new object[] {
                        soTKLK,
                        ngayMoTK,
                        email,
                        hoTen,
                        ngaySinh,
                        noiCap,
                        soCMND,
                        diaChi,
                        hanMucVay,
                        SDT});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KTThongTinSuaKHAsync(string soTKLK, System.DateTime ngayMoTK, string email, string hoTen, System.DateTime ngaySinh, string noiCap, string soCMND, string diaChi, string hanMucVay, string SDT) {
            this.KTThongTinSuaKHAsync(soTKLK, ngayMoTK, email, hoTen, ngaySinh, noiCap, soCMND, diaChi, hanMucVay, SDT, null);
        }
        
        /// <remarks/>
        public void KTThongTinSuaKHAsync(string soTKLK, System.DateTime ngayMoTK, string email, string hoTen, System.DateTime ngaySinh, string noiCap, string soCMND, string diaChi, string hanMucVay, string SDT, object userState) {
            if ((this.KTThongTinSuaKHOperationCompleted == null)) {
                this.KTThongTinSuaKHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKTThongTinSuaKHOperationCompleted);
            }
            this.InvokeAsync("KTThongTinSuaKH", new object[] {
                        soTKLK,
                        ngayMoTK,
                        email,
                        hoTen,
                        ngaySinh,
                        noiCap,
                        soCMND,
                        diaChi,
                        hanMucVay,
                        SDT}, this.KTThongTinSuaKHOperationCompleted, userState);
        }
        
        private void OnKTThongTinSuaKHOperationCompleted(object arg) {
            if ((this.KTThongTinSuaKHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KTThongTinSuaKHCompleted(this, new KTThongTinSuaKHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemKH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ThemKH(string jsonData) {
            object[] results = this.Invoke("ThemKH", new object[] {
                        jsonData});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ThemKHAsync(string jsonData) {
            this.ThemKHAsync(jsonData, null);
        }
        
        /// <remarks/>
        public void ThemKHAsync(string jsonData, object userState) {
            if ((this.ThemKHOperationCompleted == null)) {
                this.ThemKHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemKHOperationCompleted);
            }
            this.InvokeAsync("ThemKH", new object[] {
                        jsonData}, this.ThemKHOperationCompleted, userState);
        }
        
        private void OnThemKHOperationCompleted(object arg) {
            if ((this.ThemKHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemKHCompleted(this, new ThemKHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/layDSRo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string layDSRo() {
            object[] results = this.Invoke("layDSRo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void layDSRoAsync() {
            this.layDSRoAsync(null);
        }
        
        /// <remarks/>
        public void layDSRoAsync(object userState) {
            if ((this.layDSRoOperationCompleted == null)) {
                this.layDSRoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlayDSRoOperationCompleted);
            }
            this.InvokeAsync("layDSRo", new object[0], this.layDSRoOperationCompleted, userState);
        }
        
        private void OnlayDSRoOperationCompleted(object arg) {
            if ((this.layDSRoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.layDSRoCompleted(this, new layDSRoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/suaThongTinKH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool suaThongTinKH(string soTKLK, string hoTen, System.DateTime ngaySinh, string noiCap, string soCMNN, System.DateTime ngayCap, string email, string gioiTinh, int hanMucVay, string diaChi, string SDT, string maRo) {
            object[] results = this.Invoke("suaThongTinKH", new object[] {
                        soTKLK,
                        hoTen,
                        ngaySinh,
                        noiCap,
                        soCMNN,
                        ngayCap,
                        email,
                        gioiTinh,
                        hanMucVay,
                        diaChi,
                        SDT,
                        maRo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void suaThongTinKHAsync(string soTKLK, string hoTen, System.DateTime ngaySinh, string noiCap, string soCMNN, System.DateTime ngayCap, string email, string gioiTinh, int hanMucVay, string diaChi, string SDT, string maRo) {
            this.suaThongTinKHAsync(soTKLK, hoTen, ngaySinh, noiCap, soCMNN, ngayCap, email, gioiTinh, hanMucVay, diaChi, SDT, maRo, null);
        }
        
        /// <remarks/>
        public void suaThongTinKHAsync(string soTKLK, string hoTen, System.DateTime ngaySinh, string noiCap, string soCMNN, System.DateTime ngayCap, string email, string gioiTinh, int hanMucVay, string diaChi, string SDT, string maRo, object userState) {
            if ((this.suaThongTinKHOperationCompleted == null)) {
                this.suaThongTinKHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsuaThongTinKHOperationCompleted);
            }
            this.InvokeAsync("suaThongTinKH", new object[] {
                        soTKLK,
                        hoTen,
                        ngaySinh,
                        noiCap,
                        soCMNN,
                        ngayCap,
                        email,
                        gioiTinh,
                        hanMucVay,
                        diaChi,
                        SDT,
                        maRo}, this.suaThongTinKHOperationCompleted, userState);
        }
        
        private void OnsuaThongTinKHOperationCompleted(object arg) {
            if ((this.suaThongTinKHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.suaThongTinKHCompleted(this, new suaThongTinKHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void layDSKhachHangCompletedEventHandler(object sender, layDSKhachHangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class layDSKhachHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal layDSKhachHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void layMotKhachHangCompletedEventHandler(object sender, layMotKhachHangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class layMotKhachHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal layMotKhachHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetKHCompletedEventHandler(object sender, GetKHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetKHSDTCompletedEventHandler(object sender, GetKHSDTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKHSDTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKHSDTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KTThongTinThemKHCompletedEventHandler(object sender, KTThongTinThemKHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KTThongTinThemKHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KTThongTinThemKHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KTThongTinSuaKHCompletedEventHandler(object sender, KTThongTinSuaKHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KTThongTinSuaKHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KTThongTinSuaKHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ThemKHCompletedEventHandler(object sender, ThemKHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemKHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemKHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void layDSRoCompletedEventHandler(object sender, layDSRoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class layDSRoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal layDSRoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void suaThongTinKHCompletedEventHandler(object sender, suaThongTinKHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class suaThongTinKHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal suaThongTinKHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591