//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GUI.CheckWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CheckSoap", Namespace="http://tempuri.org/")]
    public partial class Check : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ChiChuaChuCaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback LaMotSoNguyenDuongOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChiChuaChuSoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Check() {
            this.Url = global::GUI.Properties.Settings.Default.GUI_CheckWS_Check;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChiChuaChuCaiCompletedEventHandler ChiChuaChuCaiCompleted;
        
        /// <remarks/>
        public event LaMotSoNguyenDuongCompletedEventHandler LaMotSoNguyenDuongCompleted;
        
        /// <remarks/>
        public event ChiChuaChuSoCompletedEventHandler ChiChuaChuSoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChiChuaChuCai", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChiChuaChuCai(string str) {
            object[] results = this.Invoke("ChiChuaChuCai", new object[] {
                        str});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChiChuaChuCaiAsync(string str) {
            this.ChiChuaChuCaiAsync(str, null);
        }
        
        /// <remarks/>
        public void ChiChuaChuCaiAsync(string str, object userState) {
            if ((this.ChiChuaChuCaiOperationCompleted == null)) {
                this.ChiChuaChuCaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChiChuaChuCaiOperationCompleted);
            }
            this.InvokeAsync("ChiChuaChuCai", new object[] {
                        str}, this.ChiChuaChuCaiOperationCompleted, userState);
        }
        
        private void OnChiChuaChuCaiOperationCompleted(object arg) {
            if ((this.ChiChuaChuCaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChiChuaChuCaiCompleted(this, new ChiChuaChuCaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LaMotSoNguyenDuong", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LaMotSoNguyenDuong(string str) {
            object[] results = this.Invoke("LaMotSoNguyenDuong", new object[] {
                        str});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LaMotSoNguyenDuongAsync(string str) {
            this.LaMotSoNguyenDuongAsync(str, null);
        }
        
        /// <remarks/>
        public void LaMotSoNguyenDuongAsync(string str, object userState) {
            if ((this.LaMotSoNguyenDuongOperationCompleted == null)) {
                this.LaMotSoNguyenDuongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLaMotSoNguyenDuongOperationCompleted);
            }
            this.InvokeAsync("LaMotSoNguyenDuong", new object[] {
                        str}, this.LaMotSoNguyenDuongOperationCompleted, userState);
        }
        
        private void OnLaMotSoNguyenDuongOperationCompleted(object arg) {
            if ((this.LaMotSoNguyenDuongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LaMotSoNguyenDuongCompleted(this, new LaMotSoNguyenDuongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChiChuaChuSo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChiChuaChuSo(string str) {
            object[] results = this.Invoke("ChiChuaChuSo", new object[] {
                        str});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChiChuaChuSoAsync(string str) {
            this.ChiChuaChuSoAsync(str, null);
        }
        
        /// <remarks/>
        public void ChiChuaChuSoAsync(string str, object userState) {
            if ((this.ChiChuaChuSoOperationCompleted == null)) {
                this.ChiChuaChuSoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChiChuaChuSoOperationCompleted);
            }
            this.InvokeAsync("ChiChuaChuSo", new object[] {
                        str}, this.ChiChuaChuSoOperationCompleted, userState);
        }
        
        private void OnChiChuaChuSoOperationCompleted(object arg) {
            if ((this.ChiChuaChuSoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChiChuaChuSoCompleted(this, new ChiChuaChuSoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ChiChuaChuCaiCompletedEventHandler(object sender, ChiChuaChuCaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChiChuaChuCaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChiChuaChuCaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LaMotSoNguyenDuongCompletedEventHandler(object sender, LaMotSoNguyenDuongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LaMotSoNguyenDuongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LaMotSoNguyenDuongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ChiChuaChuSoCompletedEventHandler(object sender, ChiChuaChuSoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChiChuaChuSoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChiChuaChuSoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591